# Generated by Django 4.0.5 on 2022-06-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TV', models.CharField(max_length=15)),
                ('Radio', models.CharField(max_length=20)),
                ('Newspaper', models.CharField(max_length=20)),
                ('Sales', models.CharField(max_length=20)),
            ],
        ),
    ]
